version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ecosystem:python
    commit-message:
      prefix: deps
      include: scope
  - package-ecosystem: npm
    directory: /apps/admin-web
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ecosystem:javascript
    commit-message:
      prefix: deps
      include: scope
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ecosystem:github-actions
    commit-message:
      prefix: deps
      include: scope
