from __future__ import annotations

import sys
from pathlib import Path

_CONTRACTS_DIR = Path(__file__).resolve().parents[3] / "packages" / "contracts"
if _CONTRACTS_DIR.is_dir():
    contracts_path = str(_CONTRACTS_DIR)
    if contracts_path not in sys.path:
        sys.path.insert(0, contracts_path)

from open_talon_contracts.models import (  # noqa: E402
    ActorRef,
    AgentArtifactDraft,
    AgentConfiguration,
    AgentDefinition,
    AgentEndpoint,
    AgentExecutionContext,
    AgentInteractionContract,
    AgentRunResult,
    AgentResponseContract,
    AgentTaskRouting,
    AssumeParticipantRoleRequest,
    ApiKeyCreate,
    ApiKeyInfo,
    Artifact,
    CreateAgentParticipantRequest,
    CreateSystemAgentRequest,
    CreateMemoryEntryRequest,
    CreateMessageRequest,
    CreateThreadRequest,
    CreateWorkspaceRequest,
    DeleteWorkspaceRequest,
    EventEnvelope,
    HealthResponse,
    Membership,
    MemoryEntry,
    ParticipantInput,
    ParticipantProfile,
    PresenceState,
    RoleDefinition,
    ServiceStatus,
    StopReason,
    Task,
    TargetRef,
    Thread,
    ThreadDetail,
    TimelineMessage,
    TimelinePage,
    UpdateSystemAgentRequest,
    UpsertRoleDefinitionRequest,
    UpdateAgentParticipantRequest,
    UpdateMemoryEntryRequest,
    Workspace,
    WorkspaceDetail,
)

__all__ = [
    "ActorRef",
    "AgentArtifactDraft",
    "AgentConfiguration",
    "AgentDefinition",
    "AgentEndpoint",
    "AgentExecutionContext",
    "AgentInteractionContract",
    "AgentRunResult",
    "AgentResponseContract",
    "AgentTaskRouting",
    "AssumeParticipantRoleRequest",
    "ApiKeyCreate",
    "ApiKeyInfo",
    "Artifact",
    "CreateAgentParticipantRequest",
    "CreateSystemAgentRequest",
    "CreateMemoryEntryRequest",
    "CreateMessageRequest",
    "CreateThreadRequest",
    "CreateWorkspaceRequest",
    "DeleteWorkspaceRequest",
    "EventEnvelope",
    "HealthResponse",
    "Membership",
    "MemoryEntry",
    "ParticipantInput",
    "ParticipantProfile",
    "PresenceState",
    "RoleDefinition",
    "ServiceStatus",
    "StopReason",
    "Task",
    "TargetRef",
    "Thread",
    "ThreadDetail",
    "TimelineMessage",
    "TimelinePage",
    "UpdateSystemAgentRequest",
    "UpsertRoleDefinitionRequest",
    "UpdateAgentParticipantRequest",
    "UpdateMemoryEntryRequest",
    "Workspace",
    "WorkspaceDetail",
]
