from __future__ import annotations

IDENTITY_PERMISSION_DESCRIPTIONS: dict[str, str] = {
    "organization.read": "Read organization metadata that is already in scope for the principal.",
    "organization.write": "Create or update organization metadata at the platform control-plane level.",
    "organization.members.read": "Read organization membership records.",
    "organization.members.write": "Add, update, or remove organization members.",
    "project.read": "Read project metadata inside an authorized organization.",
    "project.write": "Create or update projects inside an authorized organization.",
    "workspace.list": "List workspaces that belong to an authorized organization.",
    "workspace.read": "Read workspace metadata outside workspace-local participant flows.",
    "organization.runtime.read": "Read organization runtime status and overview data.",
    "organization.runtime.write": "Resume or administratively repair organization runtime work after recoverable failures.",
    "agent_catalog.read": "Read system and organization agent catalog definitions.",
    "agent_catalog.write": "Create, update, or delete system and organization agent catalog definitions.",
    "tool_catalog.read": "Read system and organization tool catalog definitions.",
    "tool_catalog.write": "Create, update, or delete system and organization tool catalog definitions.",
    "provider.llm.read": "Read stored LLM provider definitions.",
    "provider.llm.write": "Create, update, or delete LLM provider definitions.",
    "provider.llm.validate": "Run validation and health checks for LLM provider definitions.",
    "provider.memory.read": "Read stored memory provider definitions.",
    "provider.memory.write": "Create, update, or delete memory provider definitions.",
    "provider.memory.validate": "Run validation and health checks for memory provider definitions.",
    "provider.mcp.read": "Read stored external MCP server definitions.",
    "provider.mcp.write": "Create, update, or delete external MCP server definitions.",
    "provider.mcp.validate": "Run discovery and health checks for external MCP servers.",
    "external.systems.read": "Read external system definitions in an authorized scope.",
    "external.systems.write": "Create, update, or delete external system definitions.",
    "external.systems.validate": "Validate external system connectivity and authentication configuration.",
    "external.grants.read": "Read participant external identity grants in an authorized scope.",
    "external.grants.write": "Create, update, revoke, or pre-assign participant external identity grants.",
    "external.operations.approve": "Approve or reject pending external operation requests.",
    "git_registry.read": "Read registered Git repositories outside workspace-local flows.",
    "git_registry.write": "Create, update, or delete registered Git repositories outside workspace-local flows.",
    "asset_catalog.read": "Read published assets and links outside workspace-local flows.",
    "asset_catalog.publish": "Publish assets into the system or organization catalog.",
    "asset_catalog.link": "Create or update asset links for catalog targets.",
    "asset_catalog.activate": "Activate a specific published asset version for a target.",
    "library.read": "Read libraries and library items in an authorized scope.",
    "library.write": "Create, update, archive, and add items to libraries in an authorized scope.",
    "library.attach": "Attach organization or project libraries to authorized workspaces.",
    "library.index": "Request indexing for libraries and library items.",
    "retrieval.read": "Read retrieval corpora, sources, profiles, jobs, runs, and context packs.",
    "retrieval.write": "Create retrieval corpora, sources, profiles, and ingestion jobs.",
    "retrieval.search": "Search retrieval corpora and create context packs.",
    "retrieval.admin": "Manage retrieval defaults, provider overrides, and repair or reindex operations.",
    "methodology.read": "Read methodology extraction drafts and related workspace-template evidence.",
    "methodology.write": "Create methodology extraction drafts from cited retrieval/source evidence.",
    "methodics.read": "Read methodics execution runs, steps, assignments, checks, and resource requests.",
    "methodics.execute": "Start, coordinate, and cancel methodics execution runs.",
    "methodics.admin": "Approve, reject, or administratively repair methodics execution resource requests.",
    "tool_generation.read": "Read tool-generation requests through control-plane APIs.",
    "tool_generation.review": "Approve or reject tool-generation revisions.",
    "audit.read": "Read audit events for authorized scopes.",
    "audit.export": "Export audit events for authorized scopes.",
    "audit.verify": "Verify audit chain integrity for authorized scopes.",
}

WORKSPACE_PERMISSION_DESCRIPTIONS: dict[str, str] = {
    "workspace.roles.write": "Create, update, or delete workspace role definitions.",
    "workspace.agents.write": "Attach, update, or remove workspace agent participants.",
    "workspace.tools.write": "Attach, update, or detach workspace tool bindings.",
    "workspace.mcp_servers.write": "Attach, update, or detach workspace MCP server bindings.",
    "workspace.repositories.write": "Create or update workspace Git repositories.",
    "workspace.assets.publish": "Publish workspace-scoped assets from Git.",
    "workspace.assets.link": "Create or activate workspace-scoped asset links.",
    "library.read": "Read workspace-visible libraries and library items.",
    "library.write": "Create, update, archive, and add items to workspace libraries.",
    "library.attach": "Attach organization or project libraries to the workspace.",
    "library.index": "Request indexing for workspace-visible libraries and library items.",
    "retrieval.read": "Read workspace retrieval corpora, sources, profiles, jobs, runs, and context packs.",
    "retrieval.write": "Create workspace retrieval corpora, sources, profiles, and ingestion jobs.",
    "retrieval.search": "Search workspace retrieval corpora and create context packs.",
    "retrieval.admin": "Manage workspace retrieval defaults, provider overrides, and reindex operations.",
    "methodology.read": "Read workspace methodology extraction drafts and related template evidence.",
    "methodology.write": "Create workspace methodology extraction drafts from cited retrieval/source evidence.",
    "methodics.read": "Read workspace methodics execution runs, steps, assignments, checks, and resource requests.",
    "methodics.execute": "Start, coordinate, and cancel workspace methodics execution runs.",
    "methodics.admin": "Approve, reject, or administratively repair workspace methodics execution resource requests.",
    "workspace.audit.read": "Read workspace audit events.",
    "workspace.audit.export": "Export workspace audit events.",
    "workspace.audit.verify": "Verify workspace audit chains.",
}

PROJECT_PERMISSION_DESCRIPTIONS: dict[str, str] = {
    "project.read": "Read project metadata and workspace structure for a project-bound principal.",
    "project.write": "Update project metadata for a project-bound principal.",
    "project.access.write": "Create, update, or remove project access bindings.",
    "workspace.list": "List workspace structure inside a project.",
    "workspace.create": "Create workspaces inside a project.",
    "library.read": "Read project libraries and library items.",
    "library.write": "Create, update, archive, and add items to project libraries.",
    "library.attach": "Attach project libraries to authorized workspaces.",
    "library.index": "Request indexing for project libraries and library items.",
    "retrieval.read": "Read project retrieval corpora, sources, profiles, jobs, runs, and context packs.",
    "retrieval.write": "Create project retrieval corpora, sources, profiles, and ingestion jobs.",
    "retrieval.search": "Search project retrieval corpora and create context packs.",
    "retrieval.admin": "Manage project retrieval defaults, provider overrides, and reindex operations.",
}

PROJECT_ROLE_BASE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "creator": tuple(PROJECT_PERMISSION_DESCRIPTIONS),
    "owner": tuple(PROJECT_PERMISSION_DESCRIPTIONS),
    "editor": (
        "project.read",
        "project.write",
        "workspace.list",
        "workspace.create",
        "library.read",
        "library.write",
        "library.attach",
        "library.index",
        "retrieval.read",
        "retrieval.write",
        "retrieval.search",
    ),
    "viewer": (
        "project.read",
        "workspace.list",
        "library.read",
        "retrieval.read",
        "retrieval.search",
    ),
}

IDENTITY_PERMISSION_NAMES: tuple[str, ...] = tuple(IDENTITY_PERMISSION_DESCRIPTIONS.keys())
WORKSPACE_PERMISSION_NAMES: tuple[str, ...] = tuple(WORKSPACE_PERMISSION_DESCRIPTIONS.keys())

ORGANIZATION_ROLE_BASE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "owner": IDENTITY_PERMISSION_NAMES,
    "admin": (
        "organization.read",
        "organization.members.read",
        "organization.members.write",
        "project.read",
        "project.write",
        "workspace.list",
        "workspace.read",
        "organization.runtime.read",
        "organization.runtime.write",
        "agent_catalog.read",
        "agent_catalog.write",
        "tool_catalog.read",
        "tool_catalog.write",
        "provider.llm.read",
        "provider.llm.write",
        "provider.llm.validate",
        "provider.memory.read",
        "provider.memory.write",
        "provider.memory.validate",
        "provider.mcp.read",
        "provider.mcp.write",
        "provider.mcp.validate",
        "external.systems.read",
        "external.systems.write",
        "external.systems.validate",
        "external.grants.read",
        "external.grants.write",
        "external.operations.approve",
        "git_registry.read",
        "git_registry.write",
        "asset_catalog.read",
        "asset_catalog.publish",
        "asset_catalog.link",
        "asset_catalog.activate",
        "library.read",
        "library.write",
        "library.attach",
        "library.index",
        "retrieval.read",
        "retrieval.write",
        "retrieval.search",
        "retrieval.admin",
        "methodology.read",
        "methodology.write",
        "methodics.read",
        "methodics.execute",
        "methodics.admin",
        "tool_generation.read",
        "tool_generation.review",
        "audit.read",
        "audit.export",
        "audit.verify",
    ),
    "member": (
        "organization.read",
        "organization.members.read",
        "project.read",
        "workspace.list",
        "workspace.read",
        "organization.runtime.read",
        "agent_catalog.read",
        "tool_catalog.read",
        "provider.llm.read",
        "provider.memory.read",
        "provider.mcp.read",
        "external.systems.read",
        "git_registry.read",
        "asset_catalog.read",
        "library.read",
        "retrieval.read",
        "retrieval.search",
        "methodology.read",
        "methodics.read",
        "tool_generation.read",
        "audit.read",
    ),
}


__all__ = [
    "IDENTITY_PERMISSION_DESCRIPTIONS",
    "IDENTITY_PERMISSION_NAMES",
    "ORGANIZATION_ROLE_BASE_PERMISSIONS",
    "PROJECT_PERMISSION_DESCRIPTIONS",
    "PROJECT_ROLE_BASE_PERMISSIONS",
    "WORKSPACE_PERMISSION_DESCRIPTIONS",
    "WORKSPACE_PERMISSION_NAMES",
]
