from __future__ import annotations

import sys
from pathlib import Path

_CONTRACTS_DIR = Path(__file__).resolve().parents[3] / "packages" / "contracts"
if _CONTRACTS_DIR.is_dir():
    contracts_path = str(_CONTRACTS_DIR)
    if contracts_path not in sys.path:
        sys.path.insert(0, contracts_path)

from open_talon_contracts.models import (  # noqa: E402
    ActorRef,
    AgentArtifactDraft,
    AgentConfiguration,
    AgentDefinition,
    AgentEndpoint,
    AgentExecutionContext,
    AgentInteractionContract,
    AgentRunResult,
    AgentResponseContract,
    AgentTaskRouting,
    AttachWorkspaceToolRequest,
    AssumeParticipantRoleRequest,
    Artifact,
    CreateAgentParticipantRequest,
    CreateSystemAgentRequest,
    CreateMemoryEntryRequest,
    CreateMessageRequest,
    CreateSystemToolRequest,
    CreateThreadRequest,
    CreateWorkspaceRequest,
    DeleteParticipantRequest,
    DeleteWorkspaceToolRequest,
    DeleteWorkspaceRequest,
    EventEnvelope,
    Membership,
    MemoryEntry,
    ParticipantInput,
    ParticipantProfile,
    PresenceState,
    RoleDefinition,
    Run,
    SystemToolDefinition,
    StopReason,
    ToolParameterContract,
    ToolParameterDefinition,
    Task,
    TargetRef,
    Thread,
    ThreadDetail,
    TimelineMessage,
    TimelinePage,
    UpdateSystemAgentRequest,
    UpsertRoleDefinitionRequest,
    UpdateSystemToolRequest,
    UpdateAgentParticipantRequest,
    UpdateMemoryEntryRequest,
    UpdateWorkspaceToolRequest,
    Workspace,
    WorkspaceDetail,
    WorkspaceTool,
)
from open_talon_contracts.agent_contracts import (  # noqa: E402
    build_default_interaction_contract,
    interaction_contract_is_empty,
)

__all__ = [
    "ActorRef",
    "build_default_interaction_contract",
    "AgentArtifactDraft",
    "AgentConfiguration",
    "AgentDefinition",
    "AgentEndpoint",
    "AgentExecutionContext",
    "AgentInteractionContract",
    "AgentRunResult",
    "AgentResponseContract",
    "AgentTaskRouting",
    "AttachWorkspaceToolRequest",
    "AssumeParticipantRoleRequest",
    "Artifact",
    "CreateAgentParticipantRequest",
    "CreateSystemAgentRequest",
    "CreateMemoryEntryRequest",
    "CreateMessageRequest",
    "CreateSystemToolRequest",
    "CreateThreadRequest",
    "CreateWorkspaceRequest",
    "DeleteParticipantRequest",
    "DeleteWorkspaceToolRequest",
    "DeleteWorkspaceRequest",
    "EventEnvelope",
    "Membership",
    "MemoryEntry",
    "ParticipantInput",
    "ParticipantProfile",
    "PresenceState",
    "RoleDefinition",
    "Run",
    "SystemToolDefinition",
    "StopReason",
    "ToolParameterContract",
    "ToolParameterDefinition",
    "Task",
    "TargetRef",
    "Thread",
    "ThreadDetail",
    "TimelineMessage",
    "TimelinePage",
    "UpdateSystemAgentRequest",
    "UpsertRoleDefinitionRequest",
    "UpdateSystemToolRequest",
    "UpdateAgentParticipantRequest",
    "UpdateMemoryEntryRequest",
    "UpdateWorkspaceToolRequest",
    "Workspace",
    "WorkspaceDetail",
    "WorkspaceTool",
    "interaction_contract_is_empty",
]
